version: '3.4'

services:
  languagecard.api:
    image: ${DOCKER_REGISTRY-}languagecardapi
    build:
      context: .
      dockerfile: languagecard.api/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.languagecard.rule=Host(`languagecard.localhost`)"
      - "traefik.http.routers.languagecard.entrypoints=web"
    environment:
      - DATASTOREDB_HOST=datastore
      - DATASTOREDB_PROJECT=langproject
      - DATASTOREDB_PORT=8081
      - DEVMODE=true
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  datastore:
    image: milesmcc/gcp-emulator
    environment:
      - DATASTORE_PROJECT_ID=langproject
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081

  datastore-ui:
    image: skarpdev/google-datastore-ui:1.0.0
    environment:
      DSUI_PROJECT_ID: langproject
      DSUI_PORT: 8282
      DSUI_DATASTORE_ENDPOINT: datastore:8081
    ports:
      - 8282:8282
    depends_on:
      - datastore
    links:
      - datastore
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbviewer.rule=Host(`dbviewer.localhost`)"
      - "traefik.http.routers.dbviewer.entrypoints=web"
